package com.example.presentation.utils

import androidx.compose.runtime.Composable

object Localization {

    private val translations = mapOf(
        "welcome" to Pair("Welcome, ", "स्वागत है, "),
        "exam_countdown" to Pair("RPSC EO/RO Exam Countdown", "आरपीएससी ईओ/आरओ परीक्षा काउंटडाउन"),
        "days" to Pair("Days", "दिन"),
        "hours" to Pair("Hours", "घंटे"),
        "minutes" to Pair("Minutes", "मिनट"),
        "seconds" to Pair("Seconds", "सेकंड"),
        "flashcards" to Pair("Flashcards", "फ्लैशकार्ड"),
        "test_series" to Pair("Test Series", "टेस्ट सीरीज"),
        "study_progress" to Pair("Study Progress", "अध्ययन प्रगति"),
        "read_mode" to Pair("Read Mode", "पढ़ें मोड"),
        "practice_mode" to Pair("Practice Mode", "अभ्यास मोड"),
        "streak" to Pair("Daily Study Streak", "दैनिक अध्ययन स्ट्रीक"),
        "target" to Pair("Current Target", "वर्तमान लक्ष्य"),
        "avg_score" to Pair("Average Score", "औसत स्कोर"),
        "weekly" to Pair("Weekly Progress", "साप्ताहिक प्रगति"),
        "syllabus" to Pair("Syllabus", "पाठ्यक्रम"),
        "chapters" to Pair("Chapters", "अध्याय"),
        "subtopics" to Pair("Subtopics", "उपविषय"),
        "free_ch" to Pair("Free Chapter", "निःशुल्क अध्याय"),
        "locked_ch" to Pair("Premium Chapter (Tap to Unlock)", "प्रीमियम अध्याय (अनलॉक करने के लिए टैप करें)"),
        "unlocked_ch" to Pair("Unlocked Chapter", "अनलॉक किया गया अध्याय"),
        "download" to Pair("Download", "डाउनलोड"),
        "downloaded" to Pair("Downloaded", "डाउनलोड किया गया"),
        "downloading" to Pair("Downloading...", "डाउनलोड हो रहा है..."),
        "reading_time" to Pair("Reading Time: ", "पढ़ने का समय: "),
        "font_size" to Pair("Font Size", "फ़ॉन्ट आकार"),
        "line_height" to Pair("Line Height", "पंक्ति की ऊंचाई"),
        "bookmark" to Pair("Bookmark", "बुकमार्क"),
        "bookmarked" to Pair("Bookmarked", "बुकमार्क किया गया"),
        "add_note" to Pair("Add Note", "नोट जोड़ें"),
        "highlight" to Pair("Highlight", "हाइलाइट"),
        "dictionary" to Pair("Dictionary", "शब्दकोश"),
        "translation" to Pair("Translation", "अनुवाद"),
        "unlock_reward_title" to Pair("Unlock Premium Chapter", "प्रीमियम अध्याय अनलॉक करें"),
        "unlock_reward_desc" to Pair("Watch a short ad to permanently unlock this chapter.", "इस अध्याय को स्थायी रूप से अनलॉक करने के लिए एक छोटा विज्ञापन देखें।"),
        "unlock_btn" to Pair("Watch Ad & Unlock", "विज्ञापन देखें और अनलॉक करें"),
        "unlock_success" to Pair("Chapter successfully unlocked!", "अध्याय सफलतापूर्वक अनलॉक हो गया!"),
        "unlocked" to Pair("Unlocked", "अनलॉक किया गया"),
        "locked" to Pair("Locked", "लॉक्ड"),
        "mock_tests" to Pair("Mock Tests", "मॉक टेस्ट"),
        "chapter_tests" to Pair("Chapter Tests", "अध्याय परीक्षण"),
        "wrong_questions" to Pair("Wrong Questions", "गलत प्रश्न"),
        "score" to Pair("Score: ", "स्कोर: "),
        "marks" to Pair("Marks: ", "अंक: "),
        "high_score" to Pair("Highest Score: ", "उच्चतम स्कोर: "),
        "time" to Pair("Time: ", "समय: "),
        "difficulty" to Pair("Difficulty: ", "कठिनाई: "),
        "attempted" to Pair("Attempted", "प्रयास किया"),
        "not_attempted" to Pair("Not Attempted", "प्रयास नहीं किया"),
        "reattempt" to Pair("Reattempt", "पुनः प्रयास करें"),
        "locked_test_desc" to Pair("Watch a short ad to permanently unlock this test.", "इस टेस्ट को स्थायी रूप से अनलॉक करने के लिए एक छोटा विज्ञापन देखें।"),
        "preparing_result" to Pair("Preparing Your Performance...", "आपका प्रदर्शन तैयार किया जा रहा है..."),
        "total_marks" to Pair("Total Marks", "कुल अंक"),
        "correct" to Pair("Correct", "सही"),
        "incorrect" to Pair("Incorrect", "गलत"),
        "skipped" to Pair("Skipped", "छोड़े गए"),
        "accuracy" to Pair("Accuracy", "सटीकता"),
        "percentile" to Pair("Percentile", "प्रतिशतक"),
        "avg_time" to Pair("Average Time", "औसत समय"),
        "rank_estimate" to Pair("Estimated Rank", "अनुमानित रैंक"),
        "strength" to Pair("Strength", "मजबूत क्षेत्र"),
        "weak_areas" to Pair("Weak Areas", "कमजोर क्षेत्र"),
        "recommendation" to Pair("Recommendations", "सिफारिशें"),
        "retry" to Pair("Retry Test", "पुनः प्रयास करें"),
        "review_answers" to Pair("Review Answers", "उत्तरों की समीक्षा करें"),
        "share_result" to Pair("Share Result", "परिणाम साझा करें"),
        "flashcards_daily" to Pair("Daily Flashcards", "दैनिक फ्लैशकार्ड"),
        "saved_flashcards" to Pair("Saved Flashcards", "सहेजे गए फ्लैशकार्ड"),
        "recent" to Pair("Recent", "हाल ही का"),
        "favorites" to Pair("Favorites", "पसंदीदा"),
        "predict_score" to Pair("Predicted Score", "अनुमानित स्कोर"),
        "select_lang" to Pair("Select Language", "भाषा चुनें"),
        "enter_name" to Pair("Enter Your Name", "अपना नाम दर्ज करें"),
        "set_goal" to Pair("Daily Study Goal (Hours)", "दैनिक अध्ययन लक्ष्य (घंटे)"),
        "get_started" to Pair("Get Started", "शुरू करें"),
        "welcome_officer" to Pair("Welcome Officer!", "स्वागत है अधिकारी!"),
        "rpsc_subtitle" to Pair("RPSC Executive & Revenue Officer Academy", "आरपीएससी कार्यकारी एवं राजस्व अधिकारी अकादमी"),
        "language_name" to Pair("Language", "भाषा"),
        "goal_hint" to Pair("Choose your daily reading target to maintain study streak.", "अध्ययन स्ट्रीक बनाए रखने के लिए अपना दैनिक पठन लक्ष्य चुनें।"),
        "days_left" to Pair("Days Left", "दिन शेष"),
        "dark_mode" to Pair("Dark Mode", "डार्क मोड"),
        "light_mode" to Pair("Light Mode", "लाइट मोड"),
        "search_hint" to Pair("Search books or topics...", "किताबें या विषय खोजें..."),
        "filter_all" to Pair("All Parts", "सभी भाग"),
        "filter_part_a" to Pair("Part A (GK)", "भाग ए (जीके)"),
        "filter_part_b" to Pair("Part B (Act)", "भाग बी (अधिनियम)"),
        "bookmark_saved" to Pair("Saved to Bookmarks", "बुकमार्क में सहेजा गया"),
        "bookmark_removed" to Pair("Removed from Bookmarks", "बुकमार्क से हटाया गया"),
        "free_badge" to Pair("Free", "निःशुल्क"),
        "pro_badge" to Pair("Pro", "प्रीमियम"),
        "dictionary_title" to Pair("In-App Scholar Dictionary", "इन-ऐप स्कॉलर शब्दकोश"),
        "dictionary_not_found" to Pair("Word definition not cached. Keep reading!", "शब्द की परिभाषा कैश नहीं है। पढ़ते रहें!"),
        "skip_ad_btn" to Pair("Skip Ad (Use Life Skip)", "विज्ञापन छोड़ें (लाइफ स्किप का उपयोग करें)"),
        "skips_remaining" to Pair("Skips remaining (Lifetime): ", "शेष स्किप (लाइफटाइम): "),
        "no_skips_left" to Pair("No lifetime skips remaining. Please watch ad.", "कोई लाइफटाइम स्किप शेष नहीं है। कृपया विज्ञापन देखें।"),
        "flashcard_empty" to Pair("No flashcards found. Generating daily deck...", "कोई फ्लैशकार्ड नहीं मिला। दैनिक डेक तैयार किया जा रहा है..."),
        "show_answer" to Pair("Reveal Answer", "उत्तर प्रकट करें"),
        "next_card" to Pair("Next Flashcard", "अगला फ्लैशकार्ड"),
        "swipe_instruction" to Pair("Swipe right if you got it right, left to repeat!", "सही होने पर दाएं स्वाइप करें, दोहराने के लिए बाएं!"),
        "predicted_subtitle" to Pair("Expected RPSC EO RO Score", "अपेक्षित आरपीएससी ईओ आरओ स्कोर"),
        "predicted_desc" to Pair("Calculated based on chapter test accuracy and practice scores.", "अध्याय परीक्षण सटीकता और अभ्यास स्कोर के आधार पर गणना की गई।"),
        "cms_title" to Pair("Content & Update Manager", "सामग्री और अद्यतन प्रबंधक"),
        "cms_info" to Pair("Real-time content sync powered by Firestore & Storage. Local copies are stored in Room to minimize cellular data consumption.", "फायरस्टोर और स्टोरेज द्वारा संचालित रीयल-टाइम सामग्री सिंक। सेलुलर डेटा खपत को कम करने के लिए स्थानीय प्रतियां रूम में संग्रहीत की जाती हैं।")
    )

    fun getString(key: String, languageCode: String): String {
        val pair = translations[key] ?: return key
        return if (languageCode == "hi") pair.second else pair.first
    }
}
